title: Kevin Tran
description: Just A developer
show_downloads: true
google_analytics:
permalink: /posts/:slug-:year-:month-:day
exclude:
  - Gemfile
  - Gemfile.lock
paginate_path: /posts/:num/
paginate: 5
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
timezone: Asia/Singapore
