title: Kevin Tran
description: Writing Code and Grinding Coffee.
show_downloads: true
google_analytics:
permalink: /posts/:slug-:year-:month-:day
stackoverflow:
  page: http://stackoverflow.com/users/1659807/duykhoa
github:
  username: duykhoa
  page: https://github.com/duykhoa
exclude:
  - Gemfile
  - Gemfile.lock
paginate_path: /posts/:num/
paginate: 20
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
timezone: Asia/Singapore
