title: Kevin Tran
description: "`Writing Code` and _Grinding Coffee_."
show_downloads: true
google_analytics:
permalink: /posts/:slug-:year-:month-:day
stackoverflow:
  page: http://stackoverflow.com/users/1659807/duykhoa
github:
  username: duykhoa
  page: https://github.com/duykhoa
linkedin:
  page: https://www.linkedin.com/in/tranduykhoa
twitter:
  page: https://twitter.com/duykhoa12t
logo:
  url: /assets/images/avatar-resize-220x220.png
include:
  - fonts/
exclude:
  - Gemfile
  - Gemfile.lock
paginate_path: /posts/:num/
paginate: 100
pluggins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
timezone: Asia/Singapore
