baseURL = 'https://duykhoa.github.io/'
languageCode = 'en-us'
title = 'Kevin Tran'
theme = 'mini'
disqusShortname = 'https-duykhoa-github-io-1'

[Params]
mainSections = 'posts'
subtitle = 'Blog'
showToc = false 
enableComments = true
