baseURL = 'https://duykhoa.github.io/'
languageCode = 'en-us'
theme = 'hugo-bearcub'
disqusShortname = 'https-duykhoa-github-io-1'
enableRobotsTXT = true
title = "Kevin's Blog"
copyright = "Kevin Tran"

[Params]
mainSections = 'posts'
showToc = false
enableComments = true
customCSS = ['/css/custom.css']
bio = "A Developer's Journey through Web Technologies"
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[Params.author]
    name = "Kevin Tran"
    email = "duykhoa12t[at]gmail[dot]com"