baseURL = 'https://duykhoa.github.io/'
languageCode = 'en-us'
title = "Kevin Blog: A Developer's Journey through Web Technologies"
theme = 'mini'
disqusShortname = 'https-duykhoa-github-io-1'

[Params]
mainSections = 'posts'
subtitle = 'Blog'
showToc = false
enableComments = true
