baseURL = 'https://duykhoa.github.io'
languageCode = 'en-us'
title = 'Kevin Tran'
theme = 'mini'
disqusShortname = "duykhoa12t"

[Params]
mainSections = "posts"
subtitle = "Blog"
showToc = true
enableComments = true
